name: Unit Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint-format:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pip-tools
          pip install pytest pytest-asyncio

      - name: Generate and Install requirements
        run: |
          pip-compile --generate-hashes --output-file=requirements.txt pyproject.toml
          pip install -r requirements.txt

      - name: Install Forklet in editable mode
        run: pip install -e .

      - name: Run tests
        run: pytest

